### ISSUE TITLE
Play Store description wording

### ISSUE THREAD

**Issue by Alexendoo** [ccrama/Slide#2108]
@Soberat [mentioned on crowdin](https://crowdin.com/translate/slide-for-reddit/6/en-pl#1504) there's a repetition in a list so I thought it would be good to look into the wording fully see if we can't improve it
- [x] Shadowbox/gallery repetition

``` html
• Shadowbox and gallery mode support (pro)
• Paging Shadowbox and vertical Gallery view modes (Pro)
```
- [x] Data saver repetition

In `Major features` and `Other unique features` respectively, I think the wording on the latter is preferable

``` html
• Low-data-usage mode
• Data saving mode for those on low data plans
```
- [x] Make pro/Pro consistent

``` html
• Shadowbox and gallery mode support (pro)
• Ad-Block in websites (Pro)
• Paging Shadowbox and vertical Gallery view modes (Pro)
If you have Slide for Reddit Pro, ...
• Configurable multicolumn (pro)
```
- [x] Clarify/move view modes?

I think this one could go under `Customization`, it's fairly unclear what the differences between the view modes are even if you're looking at them in the app
- [x] The `Major Features` section mixes up view modes and layouts

It's also covered under `Customization`

``` html
• 4 view modes: View huge cards with images or super-compact desktop mode for power users!
```
- [x] There're two line breaks between `View modes` and `Offline`
- [x] Update the colours/themes etc. numbers, I assume they've changed by now
- [x] `Slide also has three main layout types: [list of 5 types]`
- [ ] Potentially confusing

I wouldn't imagine the majority of users know what some of these mean

``` html
• Inline comment support
• Subreddit color api integration
```

---
- [x] [Selftext listed twice](https://crowdin.com/translate/slide-for-reddit/6/en-pl#1527)
- [ ] [Typo in word "filter"](https://crowdin.com/translate/slide-for-reddit/6/en-it#1526)

<details>
<summary>

Full play store description</summary>

``` html
<b>Slide for Reddit is a rock-solid material-designed unofficial browser for Reddit with an easy to use UI and tons of customization. Slide is ad-free, open source, and is packed with many unique features!</b>

<b>Major features</b>
• Browse Slide fully offline! There is no longer a need to have an offline browser installed
• Subreddit colors (make each sub unique!)
• 1800 theme combinations, make Slide truly unique!
• View images, gifs, albums, Vid.me, Streamable, Gyfcat, and Imgur links in the app
• Support for Live Threads
• Full moderation suite
• Reply to comments and submissions inline, and upload images straight to your submissions/comments
• Shadowbox and gallery mode support (pro)
• Filters support (link, text, title, and subreddit)
• Edit and create Multireddits
• Low-data-usage mode
• 4 view modes: View huge cards with images or super-compact desktop mode for power users!
• Synccit integration
• Ad-Block in websites (Pro)
• Paging Shadowbox and vertical Gallery view modes (Pro)
• <b>Much more!</b>

<b>View modes</b>
• Slide has three main view modes:
• Subreddit overview: view subreddits in a side-by-side layout
• No subreddit tabs: View one sub at a time
• Comment pane: View comments in a swipable page next to submissions, never lose your place in comments again!


<b>Offline</b>
Slide supports fully syncing for offline, and can even keep albums and gifs for those long commutes

<b>Customization</b>
Slide has support for 50 main colors, 9 accent colors, and 4 base themes including light, dark, dark blue, and AMOLED black. This means there are over 1,800 theme combinations to choose from!

Slide also has three main layout types:
• Card with big picture
• Card with thumbnail
• Super-compact desktop layout
• Center cropped card
• List

Along with this, you can choose whether to hide or show the actionbar and add/remove items from the actionbar.

Slide also has many font options with the ability to choose font sizes and Roboto font types!

<b>Content filters</b>
Only want to see gifs in /r/all? You can enable content fitlers to hide or show content on a per-subreddit basis! This can apply to images, selftext, links, gifs, NSFW content, and selftext

<b>Backup and Restore</b>
If you have Slide for Reddit Pro, you can backup and restore all your settings to the cloud (Google Drive), or to file! With file backup, you can save without personal information so you can share your Slide layout and theme configs with your friends!

<b>Other unique features</b>
• Streamable.com, Imgur (albums, gifs, and images), and Gyfcat support
• Full mod tools support including flairs, reports, approval, and stickying
• Edit and create multireddits
• Keep track of subs without subscribing
• Add collections of subs (like private multireddits)
• Inline comment support
• Upload images to comments, private messages, submissions, and replies
• Discover browser for finding new subreddits
• Open certain domains externally
• Full submission filter support (domains, text, title, and subreddit)
• History settings
• Synccit integration
• Ponymotes integration
• <b>FULL</b> markdown support including inline tables and code
• Subreddit color api integration
• Supports over 400 embedded content sites
• Data saving mode for those on low data plans
• Mark submissions as read on scroll
• Configurable multicolumn (pro)
• Hundreds of settings, configure Slide just how you want it!
```

</details>

**Comment by Alexendoo** [comment]
Also https://crowdin.com/translate/slide-for-reddit/6/en-pl#1527

**Comment by l3d00m** [comment]
Offline mode is kinda repeated as well.

**Comment by ccrama** [comment]
Done! Updated both the main description and also the pro store description (also changed up the formatting to make it more appealing)
